### ISSUE TITLE
plexignore not working with nested subdirectories

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-plugins/Scanners.bundle#37]
Forum reports:
https://forums.plexapp.com/index.php/topic/84401-plexignore-not-drilling-down-subfolders-anymore/
https://forums.plexapp.com/index.php/topic/83461-plexignore-not-working/

Report that .plexignore gets applied for the main directory and one subdirectory, but that if there are nested subdirectories those do not get it applied.

**Comment by arabesc** [comment]
Still doesn't work for me on the FreeBSD 10.2 / plexmediaserver-0.9.12.19.1537

There's folder structure:
/storage/media/personal/my_name/
/storage/media/personal/my_name/.plexignore
/storage/media/personal/my_name/event_name1/
/storage/media/personal/my_name/event_name1/_private/*.jpg
/storage/media/personal/my_name/event_name1/date1/*.jpg
/storage/media/personal/my_name/event_name1/date2/*.jpg
etc

Base folder for the photos is:
/storage/media/personal/my_name/

.plexignore contents:
*/_private/*
*/_PRIVATE/*
_private/*
_PRIVATE/*

Contents of the _private folder is indexed by Plex and is visible in the photo album.

**Comment by arabesc** [comment]
Was it fixed? Which PMS version contains the fix? I'm using plexmediaserver-plexpass-0.9.14.4.1556 and the folders from the .plexignore list are still here.

**Comment by maxGreenblatt** [comment]
Hi @arabesc - unfortunately we are doing some unrelated work on _all_ of `.bundle`s so this fix was not included in the latest release. Hopefully, it will make a release soon.

**Comment by arabesc** [comment]
It's partially working in the plexmediaserver-plexpass-0.9.15.0.1621

Folders:
/storage/media/personal/my_name/
/storage/media/personal/my_name/.plexignore
/storage/media/personal/my_name/event_name1/
/storage/media/personal/my_name/event_name1/_raw/\*.x3f
/storage/media/personal/my_name/event_name1/_private/name/\*.jpg
/storage/media/personal/my_name/event_name1/date1/\*.jpg
/storage/media/personal/my_name/event_name1/date2/\*.jpg

.plexignore contents:
_raw/\*
_private/\*
Result: "_private" is indexed, "_raw" isn't indexed.

.plexignore contents:
\*/_raw/\*
\*/_private/\*
Result: "_private" isn't indexed, "_raw" is indexed.

.plexignore contents:
_raw/\*
\*/_private/\*
Result: "_private" isn't indexed, "_raw" isn't indexed.

The behavior is inconsistent.

**Comment by maxGreenblatt** [comment]
Hmm, interesting - I will take a look.

Thanks for the update

**Comment by maxGreenblatt** [comment]
Hey @arabesc -

I was unable to repro your issue. Given your file structure (and the location of your `.plexignore`) as listed above none of your `.plexignore` contents filtered out the folders you want.

If you had placed your `.plexignore` in the root directory, then any of the combinations _should_ filter out the folders you want filtered. 

Also, please note that once something has been added to the library it won't get removed if you later change the `.plexignore`. So once something is scanned in - it's there for good. You can remove the item, edit the `.plexignore` and add it back, and then it won't appear as part of the library.

I'm going to close this again, but feel free to re-open if I misunderstood.

**Comment by maxGreenblatt** [comment]
Sorry - parts of my last comment are wrong! Please disregard - here is the corrected:

I was unable to repro any inconsistencies. You want to place your `.plexignore` in the root of the directory. And you want to use:

_raw/*
_private/*

but do NOT use:

*/_raw/*
*/_private/*

Also I was wrong about:
>Also, please note that once something has been added to the library it won't get removed if you later change the .plexignore. So once something is scanned in - it's there for good. You can remove the item, edit the .plexignore and add it back, and then it won't appear as part of the library.

So you CAN change the .plexignore at will and it will hide things from your library accordingly.

Sorry about the confusion!

**Comment by arabesc** [comment]
I've just changed .plexignore contents to this:

\_raw/\*
raw/\*
\_bad/\*
bad/\*
\_private/\*
*.ARW

The folder structure is:

/storage/media/personal/my\_name/    **<-- it's root**
/storage/media/personal/my\_name/.plexignore
/storage/media/personal/my\_name/event\_name1/
_/storage/media/personal/my\_name/event\_name1/\_raw/\*.x3f_    **<-- has been filtered**
/storage/media/personal/my\_name/event\_name1/\_private/name/\*.jpg
/storage/media/personal/my\_name/event\_name1/\_private/name/Canon/\*.jpg
/storage/media/personal/my\_name/event\_name1/\_private/name/Olympus/\*.jpg
_/storage/media/personal/my\_name/event\_name1/\_private/name/\_raw/\*.x3f_    **<-- has been filtered**
/storage/media/personal/my\_name/event\_name1/date1/\*.jpg
/storage/media/personal/my\_name/event\_name1/date2/\*.jpg

_.../event\_name1/\_raw/\*_ and _.../event\_name1/\_private/name/\_raw/\*_ folders have been filtered.
All other folders have been indexed.

**Comment by maxGreenblatt** [comment]
Hmm - @arabesc, can I get a platform and version number?

**Comment by maxGreenblatt** [comment]
Nevermind, I can repro the sub-folders of a blocked folder. I'll see if I can get a fix in for this

**Comment by sa2000a** [comment]
What is the current state of incorporating the solution provided by forum user tobytl (https://forums.plex.tv/profile/tobytl) here
https://forums.plex.tv/discussion/123690/usage-of-plexignore/p1#Comment_742797
and raised as GHI #56 

Has that code already gone into the scanners.bundle ? Just wanted to be sure we did not lose what looked like useful input back in october 2014

**Comment by arabesc** [comment]
@maxGreenblatt it's [plexmediaserver-plexpass-0.9.15.0.1621_1](https://freshports.org/multimedia/plexmediaserver-plexpass/) / FreeBSD v10.2.

**Comment by maxGreenblatt** [comment]
Thanks for the fixed link @sa2000a - I read through the whole thread, but could never figure out which comment was being referenced in the new forum.

I have realized that our problems are due to a limitation of `glob` and have changed the way we do things to be like the way suggested by tobytl.

Checking the fix in now for ninja testing and hopefully the fix will be the in the wild in the near future.

**Comment by sa2000a** [comment]
@maxGreenblatt The link to the old forum post stopped working after migration because of the different syntax for specific posts between the two forums. I have today adjusted the links to be in line with the new forum.  https://forums.plex.tv/discussion/comment/742797/#Comment_742797

The suggested changes were shown as diffs in the two spoilers and hopefully in line with the changes you already made

Fix 1 (diff)
```
@
   # Add glob matches from .plexignore before whacking.
   for pattern in plexignore_dirs:
     for match in glob.glob(pattern):
+      # Use normpath to convert any stray '/' from glob into os.sep (for windows), also remove trailing '/'
+      match = os.path.normpath(match)
       if os.path.isdir(match):
-        dirs_to_whack.append(os.path.dirname(match))
+        dirs_to_whack.append(match)
       else:
         files_to_whack.append(match)
``` 
and the diff for the extended functionality extracted from the 2nd spoiler in that post
```
@
 IGNORE_DIRS = ['@
         break
 
   # Add glob matches from .plexignore before whacking.
-  for pattern in plexignore_dirs:
-    for match in glob.glob(pattern):
-      if os.path.isdir(match):
-        dirs_to_whack.append(os.path.dirname(match))
-      else:
-        files_to_whack.append(match)
+  # Extend with list comprehension, slightly more efficient
+  dirs_to_whack.extend([dir for rx in plexignore_dirs for dir in subdirs if re.match(rx, os.path.normcase(dir))])
+  files_to_whack.extend([file for rx in plexignore_dirs for file in files if re.match(rx, os.path.normcase(file))])
 
   # Whack files.
   files_to_whack = list(set(files_to_whack))
```

**Comment by stephen304** [comment]
I'm having issues with `.plexignore`, my files are as follows:

```
Movies
|- .plexignore
|- Movie (xxxx)
|  |- Movie (xxxx).mp4
|  |- IGNORE.mp4
|- Movie2 (xxxx)
   |- Movie2 (xxxx).mp4
   |- IGNORE.mp4
```

My .plexignore contains:
```
IGNORE.mp4
```
Though IGNORE.mp4 still shows up in my library.

I also tried:
```
*/IGNORE.mp4
```

But that causes everything to be ignored for some reason... I'm on 1.1.4.2757 on FreeBSD (freenas)
