### ISSUE TITLE
Next error after fixing CleanPass issue in Plex iTunes Scanner

### ISSUE THREAD

**Issue by sa2000a** [plexinc-plugins/Scanners.bundle#54]
Thanks Mike for the fix for CleanPass for the iTunes Scanner. It has gone much further now but still failed. No obvious information in the exception logged message to indicate what the issue is. Might need some extra debugging code - or you decide to ditch the scanner and advise users on how to configure using the standard scanner. See https://forums.plex.tv/index.php/topic/129210-itunes-scanner-giving-a-python-error/?p=786689

The last few lines in the scanner log:
Dec 07, 2014 10:59:06:422 [12524] DEBUG - HTTP requesting to: http://127.0.0.1:32400/:/metadata/notify/create?librarySectionID=8&ids=28192&types=10
Dec 07, 2014 10:59:06:436 [12524] DEBUG - Added new media item with ID=37011 (album=Ave%20Maria%20-%20Sacred%20Arias%20and%20Choruses&artist=01%20Various&disc=1&index=0&name=Bach%20-%20Jesu%20bleibet%20meine%20Fre&title=)

Dec 07, 2014 10:59:06:468 [12524] DEBUG - Added new media part with ID=37020 [P:/ServerFolders/Media/Music/iTunes/iTunes Media/Music/01 Various/Ave Maria - Sacred Arias and Choruses/Bach - Jesu bleibet meine Fre.mp3]

Dec 07, 2014 10:59:06:468 [12524] WARN - Held transaction for too long (Library\MetadataItem.cpp:1753): 0.101000 seconds

Dec 07, 2014 10:59:06:483 [12524] ERROR - Exception assimilating media item in : Couldn't convert Python string.
Dec 07, 2014 10:59:06:484 [12524] ERROR - Exception assimilating media item in : Couldn't convert Python string.
Dec 07, 2014 10:59:06:484 [12524] ERROR - Exception assimilating media item in : Couldn't convert Python string.
Dec 07, 2014 10:59:06:484 [12524] ERROR - Exception assimilating media item in : Couldn't convert Python string.

**Comment by maxGreenblatt** [comment]
Closing since we can't repro. Re-open if this is still an issue.
