### ISSUE TITLE
Outcome of investigations into .plexignore issues

### ISSUE THREAD

**Issue by sa2000a** [plexinc-plugins/Scanners.bundle#56]
Please could you look into the detailed work carried out by tobytl in October 2014 and outlined here 
https://forums.plex.tv/index.php/topic/123690-usage-of-plexignore/?p=742797
relating to flaws in the .plexignore implementation.

Hopefully it is straightforward and obvious for you and that you will be able to incorporate the suggested changes to the code

Thanks

**Comment by maxGreenblatt** [comment]
There have been improvements to .plexignore in the last year and there are more fixes pending in the pipeline.

**Comment by maxGreenblatt** [comment]
We have fixed the problem (and the fix is live in the wild) - though I didn't make any of the requested enhancements (ie. we don't look up the tree at all plexignores, just the root and the one in the current folder).

I'm closing this for now, if we want the enhancements, let me know.

**Comment by dgw** [comment]
I do believe that having .plexignore function like .htaccess in terms of affecting subdirectories would be a good thing.
