### ISSUE TITLE
Movies scanner remove multiple instances of garbage tokens

### ISSUE THREAD

**Issue by flz** [plexinc-plugins/Scanners.bundle#57]
This causes issues with movies with "garbage" tokens both in the movie name and the trailing metadata.

Sample patch here: https://gist.github.com/anonymous/5075befb7e7e396611a1

**Comment by elan** [comment]
Can you give a few specific examples of real-life scenarios?

(Thanks for the patch!)

**Comment by flz** [comment]
I hit the issue on an internal release of Internal Affairs (which is actually mentioned in the code).

There's a bug in the previous diff (missing 'not'), you'll want https://gist.github.com/flz/72e2d8c0bd4446431c2c.

Too lazy to checkout the code and create a pull request, apologies :-)
