### ISSUE TITLE
Crash on QNAP scanner - appears to be EXIF Data related

### ISSUE THREAD

**Issue by sa2000a** [plexinc-plugins/Scanners.bundle#60]
Would like crash dump and sample photos looked into for a crash on PMS 0.9.11.7 on QNAP. User has narrowed problem down to EXIF data.

See https://forums.plex.tv/index.php/topic/153174-plex-scanner-is-apparently-unhappy-with-exif-in-certain-photos/

Crash Dump and Scanner log for the test photo library section (2 images - one good one gives crash): 
https://forums.plex.tv/index.php/topic/153174-plex-scanner-is-apparently-unhappy-with-exif-in-certain-photos/?p=881288

**Comment by elan** [comment]
Can we get a photo uploaded which causes the crash?

**Comment by elan** [comment]
Ah, my bad, it looks like he already provided them.

**Comment by elan** [comment]
And actually, this is the wrong place for this issue; please file internally in the media server issues repo; the scanner is part of that project.

**Comment by ukdtom** [comment]
And I can confirm this issue on an Arm-x19 QNAP device

**Comment by sa2000a** [comment]
Raised on server issues
