### ISSUE TITLE
Ignored numbers in square brackets

### ISSUE THREAD

**Issue by mizunokazumi** [plexinc-plugins/Scanners.bundle#62]
Tokenayzer in Contents/Resources/Common/VideoFiles.py:CleanName removes all '[bla-bla]'.

    # Take out things in brackets. (sub acts weird here, so we have to do it a few times)
    done = False
    while done == False:
      (name, count) = re.subn(r'\[[^\]]+\]', '', name, re.IGNORECASE)
      if count == 0:
        done = True

This is wrong.
They may contain a number of episodes.
For example:

    [FOSKY][Makai_Senki_Disgaea][dvdrip][01][x264_mp3][GB_BIG5].mkv
    [FOSKY][Makai_Senki_Disgaea][dvdrip][02][x264_mp3][GB_BIG5].mkv

**Comment by mmccurdy07** [comment]
It's probably possible to come up with a counterexample for every heuristic we have. I can't say I've ever seen this one in the wild, so I'm pretty confident saying it's not widespread. _Not_ stripping things in brackets would almost certainly lead to undesirable false positives for many people.

I'm going to close this one ("won't fix"), but happy to consider more examples or evidence of people having the same issue.

**Comment by mizunokazumi** [comment]
Well, okey.
And as the "last chance" when all other tests have failed, just look for '\[(?P<ep>[0-9]{1,3})\]'  in a row?
It's better than to ignore the file?
https://github.com/mizunokazumi/Scanners.bundle/commit/3a3aea0a0a40ac90db4cb5fe5120ba7ac6ab7563

Frankly, ignoring the video files gives a lot of inconvenience.
I have hundreds of folders with serials and plex shows me that, in some folders, only a couple of episodes, but in fact a lot of them there. Accordingly, I can not see them. Or worse, to think that the series lost. 
Personally, I would be more comfortable if unrecognized displayed as a series of 'unknown 1', 'unknown 2' or even somehow.
