### ISSUE TITLE
The Killing Season scans as The Killing

### ISSUE THREAD

**Issue by mmccurdy** [plexinc-plugins/Scanners.bundle#63]
https://forums.plex.tv/index.php/topic/168540-incorrect-match-when-season-is-part-of-show-title/

**Comment by maxGreenblatt** [comment]
Would just be a special case fix or is there something we can do generally?

**Comment by elan** [comment]
We could probably check for numbers after season and strip it only in that case???

**Comment by maxGreenblatt** [comment]
I just tried to repro this and couldn't.

Both `The\ Killing\ Season/Season\ 01/The.Killing.Season.S01E01.mkv` and `The\ Killing\ Season/The.Killing.Season.S01E01.mkv` matched as `The Killing Season` correctly on my dev build on master.

I also pinged the OP in the forum post, but I'm closing this for now.

**Comment by maxGreenblatt** [comment]
PS - our scanner does seem to always check that if the word `Season` is in a title or folder name that there are digits right after
