### ISSUE TITLE
Episode 264 Not Recognized

### ISSUE THREAD

**Issue by jmjf** [plexinc-plugins/Scanners.bundle#64]
Please remove 264 from the list of format strings in VideoFiles.py.

Based on testing and log output (https://forums.plex.tv/messages/31852#91458), VideoFiles.CleanName now removes 264 from filenames.

[This commit](https://github.com/plexinc-plugins/Scanners.bundle/commit/6b95b9729068292e861b50e23f67c906f9219c97) added "264" to the list of format strings in VideoFiles.py.

Assuming that 264 in a filename means "H.264" is a large logical leap. Anime series demonstrate many exceptions.

More than a few anime series have an episode 264 and arrive with absolute numbered file names. For example, *Meitantei Conan* (currently approaching episode 800), *Bleach* (over 360 episodes), *Naruto Shippuden* (over 400), *One Piece* (over 700), and *Dragon Ball Z* (291). Renumbering absolute numbered files to SxxExx format or breaking into Season-xx directories with relative-numbered filenames for any series with 264 or more episodes is a pain. 

To solve this problem, Plex users created custom scanners such as BABS and ASS available in Plex Forums). Now, BABS (see forum link above), and possibly ASS, skip episode 264 because VideoFiles.CleanName removes 264, making episode 264 undetectable.

Please support your long-time users, and logic (264 != H.264) and remove 264 from the list of format strings in VideoFiles.py. I also suggest "h" is a questionable entry in the formats list.

For reference, BABS uses the list of regexes below to detect several format strings and has, after scanning thousands of episodes, never removed something it shouldn't. Regexes may be a safer way to detect formats.
```
['([hHx][\.]?264)[^0-9]', '[^[0-9](720[pP])', '[^[0-9](1080[pP])', '[^[0-9](480[pP])']
```

**Comment by mmccurdy** [comment]
The forum link appears to be broken so I'm not totally sure what discussion you're referring to.

Can you provide some real-world examples of filenames that are problematic? Having the token `264` in the filename does not cause it to be skipped, these are only used as heuristics to clean up titles from filenames.

**Comment by jmjf** [comment]
Sure.

First, here's the forum link when I browse to the discussion, which may be helpful for more detail. https://forums.plex.tv/messages/31852

The person who submitted the question on the forum has a file named `Dragon Ball Z - 264 - Search For Survivors.mkv` (after stripping directory pathing).

The scanner removes the series title from the filename and sends `X - 264 - Search For Survivors` to VideoFiles.CleanNames. The return value is `X Search for Survivors`. The scanner can't find an episode number that matches any of its regex strings, so can't process the episode further.

For a file named `Dragon Ball Z - 263 - A Whole New Gohan.mkv`, the input to VideoFiles.CleanNames is `X - 263 - A Whole New Gohan` and the return value is `X 263 a Whole New Gohan`.

Based on that, it seems something in VideoFiles.CleanNames is removing 264 from the name. The commit I mentioned seems like the likely candidate. I could be wrong. Maybe something else in VideoFiles.CleanNames is the issue. I have series that did scan and process episodes numbered 264, a couple of years ago. The scanner code hasn't changed for two years, except to add updated logging to track this issue (was failing before logging added). Given that history and the log output, this seems to be in VideoFiles.CleanNames.

Relevant log segment for episode 263
```
2015-09-29 19:12:58 BABS: dealing with episode? file = |Dragon Ball Z - 263 - A Whole New Gohan|
2015-09-29 19:12:58 BABS: before CleanName, remove show, show = |Dragon Ball Z| file = |X - 263 - A Whole New Gohan|
2015-09-29 19:12:58 BABS: episodes: CleanName: file = |X 263 a Whole New Gohan| year = |None|
2015-09-29 19:12:58 BABS: after CleanName, remove show, show = |Dragon Ball Z| file = |X 263 a Whole New Gohan|
2015-09-29 19:12:58 BABS: matched just_episode_regexs %s.*?[ \.\-_](?P<ep>[0-9]{2,3})[^0-9c-uw-z%]+
2015-09-29 19:12:58 BABS: the_season = 1
2015-09-29 19:12:58 BABS: show = |Dragon Ball Z| the_episode = |263|
```
Episode 264
```
2015-09-29 19:12:58 BABS: dealing with episode? file = |Dragon Ball Z - 264 - Search For Survivors|
2015-09-29 19:12:58 BABS: before CleanName, remove show, show = |Dragon Ball Z| file = |X - 264 - Search For Survivors|
2015-09-29 19:12:58 BABS: episodes: CleanName: file = |X Search for Survivors| year = |None|
2015-09-29 19:12:58 BABS: after CleanName, remove show, show = |Dragon Ball Z| file = |X Search for Survivors|
2015-09-29 19:12:58 Got nothing for: X Search for Survivors
```

Relevant portion of scanner code. Note episode 264 does not get the "matched just_episode_regexes" message, which makes sense because VideoFiles.CleanName removed the episode number.
```python
          Log("BABS: dealing with episode? file = |%s|" % (file))

          # BABS -- Before we do CleanName, which will remove any dashes, etc. in filename, attempt to remove series name found in directory
          file = re.sub(show, 'X', file)
          Log("BABS: before CleanName, remove show, show = |%s| file = |%s|" % (show, file))

          # OK, next let's see if we're dealing with something that looks like an episode.
          # Begin by cleaning the filename to remove garbage like "h.264" that could throw
          # things off.
          #
          (file, year) = VideoFiles.CleanName(file)

          Log("BABS: episodes: CleanName: file = |%s| year = |%s|" % (file, year))

          # BABS -- And do it again, just in case the directory is off by things CleanName handles
          file = re.sub(show, 'X', file)
          Log("BABS: after CleanName, remove show, show = |%s| file = |%s|" % (show, file))
          
          for rx in just_episode_regexs:
            episode_match = re.search(rx, file, re.IGNORECASE)
            if episode_match is not None:

              Log("BABS: matched just_episode_regexs %s" + rx)
```

Let me know if I can provide additional information to help narrow down.

**Comment by mmccurdy** [comment]
> First, here's the forum link when I browse to the discussion, which may be helpful for more detail.

Sorry, that's still broken for me. Is this a private message conversation or something? Can you get a link to the thread itself.

It's the intent of VideoFiles.CleanName to return clean names, so I would submit that it's working as intended here. The BABS scanner is a third party scanner so I'm not entirely sure how they're using that method, but I don't believe this is an issue with the official Scanner itself. I suggest you raise the issue with the BABS author/maintainer instead.

**Comment by jmjf** [comment]
I am the BABS maintainer, so that last suggestion doesn't work. 

A user on the forums raised the issue. I updated the logging in the scanner code. User returned a log. I found that the filename going into VideoFiles.CleanName includes 264, but coming out of VideoFiles.CleanName does not.

It may be a private message thread. I added mmccurdy to the conversation, so maybe it will work for you now. If not, I'll post a link to a PDF of the thread on GoogleDrive tomorrow.

But, you may want to look at the log segments I provided for epsiode 263, which works, and episode 264, which doesn't, and the code segment I provided that generated those log segments. You can see the Log calls that write each line. You can see that the only executable code between the second call to Log, which outputs
```
BABS: before CleanName, remove show, show = |Dragon Ball Z| file = |X - 264 - Search For Survivors|
```
and the third call, which outputs
```
BABS: episodes: CleanName: file = |X Search for Survivors| year = |None|
```
is the line
```python
(file, year) = VideoFiles.CleanName(file)
```
So unless Python is somehow deciding to remove 264 on its own with that line, VideoFiles.CleanName is removing the 264.

You can also see that episode 263 does not have this problem, implying that, somewhere, CleanName is explicitly looking for and removing 264.
```
BABS: before CleanName, remove show, show = |Dragon Ball Z| file = |X - 263 - A Whole New Gohan|
BABS: episodes: CleanName: file = |X 263 a Whole New Gohan| year = |None|
```
All the log and code in this message are copied from the previous message.

**Comment by mmccurdy** [comment]
> I am the BABS maintainer, so that last suggestion doesn't work.

Ah, sorry, missed that :)

> So unless Python is somehow deciding to remove 264 on its own with that line, VideoFiles.CleanName is removing the 264.

That's correct, that's what it's doing, and that's by design (in fact it's probably not ideal that the `263` is _not_ stripped there). The intent of that function is to clean the filename and make it human-readable, so things that are not part of the title are not desired in the result.

It would be much more reliable to look for episode numbers and any other data you need (via whatever pattern matching/regex/etc. you see fit) in the filename _before_ cleaning it. Have a look at what the official series scanner does here: https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L61

Of course you're also perfectly welcome to implement your own flavor of CleanName in your own Scanner/Agent that does exactly what you need.

Thanks for your work on BABS...  I know lots of folks appreciate it!

**Comment by jmjf** [comment]
I'm not sure having the episode number (263, 264, etc.) in the filename makes it harder for humans to read. CleanNames assumes that 264 without an h or x nearby means h.264 or x264 and should be discarded. I'd be curious to hear more about the community has many cases of this naming pattern.

While absolute numbering may not be the preferred standard, Plex has allowed it in the past and scanner like BABS have made it work well. The official scanner attempts to support absolute numbering in the just_episode_regexes at [line 28](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L28). Line 31 uses ep263 as an example, so someone contemplated large episode numbers. (This line is one of the problems BABS fixes--only look for e, ep, or episode, not e followed by any arbitrary string of letters.) For some series (300+ episodes absolutely numbered), renumbering to the preferred standard isn't practical.

Implementing the assertion that episode numbers should be stripped will break the official scanner too. The section after [line 288](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L288) is attempting to handle episode-number only names with the just_episode_regexes in line 28. The first thing it does is CleanNames, which means episode numbers would be stripped and the whole section becomes dead code.

If you compare that section of the scanner code with the BABS code segment posted in https://github.com/plexinc-plugins/Scanners.bundle/issues/64#issuecomment-144836665, you'll probably see that the only difference, other than logging, is that BABS tries to remove the series name before and after the call to CleanNames. (Most of the comments are even the same. :o) I remove the series name because *Galaxy Express 999*, *Eureka 7*, and *Figure 17*, among others, scored false hits on the episode number regexes.

Making it more like the official scanner won't fix the problem because BABS is an almost exact clone of the official scanner logic for this class of filenames.

**Comment by mmccurdy** [comment]
The official patterns (e.g. `ep264`) are unambiguous and are not stripped in CleanName, so this is not an issue for the official scanner.

This is not difficult to work around in your own scanner (by all means, copy CleanName and apply whatever logic you want), but unless you can point to a bug or issue this raises in the official one, I can't justify making this change.

**Comment by jmjf** [comment]
In the official scanner regexes, the official patterns are ambiguous.

In the official scanner, all regexes in [just_episode_regexes](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L28) allow 3-digit episode numbers. For example, the following regexes in the official scanner match 264 as an episode number in the [pythex.org](http://pythex.org/) regular expression tester. (Assumption: pythex is a reliable regex reference.)
[Line 32](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L32) matches 264 in "X - 264 - Search For Survivors" (the specific example that is failing)
[Line 33](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L33) matches 264 in "X - 264" or "Joe Blow 264"
[Line 35](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L35) matches 264 in "264"

All just_episode_regexes are processed with the code beginning on [line 288](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L288). The first thing this block of code does is CleanNames, which will remove 264 from most, if not all, of the cases--but not 263, 265, or any other 3-digit number.

In the official scanner, the regex in [line 13](https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py#L13), treats a three digit number as 1-digit season + 2-digit episode. The regex in line 13 processes before the regexes in lines 32, 33, and 35. The just_episode_regexes are never processed for a three-digit episode.  (I've never seen episodes numbered that way, and it seems to set people up for a world of hurt if a series runs more than 9 seasons.)

Why write just_episode_regexes to allow 3-digit episodes if the developers don't intend the scanner run for 3-digit episodes? If the developers only intend to support 2-digit episode numbers, just_episode_regexes should not allow 3-digit episodes. If the developers don't intend to support 3-digit episode numbers, CleanNames should remove all stand-alone 3-digit numbers to be consistent.

The official regexes should be consistent and unambiguous and CleanNames should align with consistent official regexes, whatever they end up being. The inconsistency in the scanner regexes misleads third-party scanner developers. Changes justified by those inconsistencies (like adding 264 to the formats list) and inconsistent behavior resulting from those changes (removing 264 from names, but not any other 3-digit number) complicate their lives.

I'd like you to move in favor of 3-digit episodes and supporting the third-party scanner developers who make Plex attractive to a larger user community. Given the evidence that including 264 in formats causes harm to the user community, and the lack of evidence that excluding 264 from formats causes harm, and the simplicity of removing 264 from formats, it seems like Plex would decide in favor of not harming the user community.

Meanwhile, all scanner developers need to be aware of this issue, so I'll document the issue and post on the Scanners forum with a link back to this GitHub issue. I'll also try to track down people who've published scanners on the forums and point them to the forum posts so they're aware of the issue.

Because I want to support the Plex anime community and others who need support for absolute numbered episodes, I'll also work on packaging a version of BABS with a copy of VideoFiles.py that removes the 264 from format, outline the issue, and post that on the forum too.

If you decide to establish consistency in the official scanner regexes and CleanNames treatment of 3-digit episode numbers, please let me know so I can document accordingly.

**Comment by mmccurdy** [comment]
To be clear, the official pattern for three-digit episode numbers is `ep123`, which is not removed by CleanNames, is unambiguous, and to my knowledge works fine in all cases. 

The stripping of `264` specifically helps many more people than it hurts (it was added based on multiple reports of `264` erroneously showing up in titles, since it's a string that occurs frequently in filenames to indicate codec, so there was in fact evidence of this causing harm). 

If CleanNames were expanded to strip all trailing numbers (e.g.), that might appear slightly more consistent, but it would also be likely to cause at least as much harm as good (episodes are frequently titled things like "Episode N", etc.)

It's unfortunate that we can't easily support three-digit episode numbering more formally, but to do so by simply modifying the three-digit episode regex (which parses the pattern as \[season\]\[two-digit-episode\], and always has) would introduce a breaking change for existing users who may have chosen to name their media accordingly. A better solution for now is to explicitly use a Scanner (such as BABS) that has a different interpretation when that behavior is desired. We're _definitely_ aware that folks want absolute episode numbering, and it's on our list to fix it the right way (with strong support on a per-series basis), but unfortunately it's not a trivial change so it hasn't yet made it to the top.

The utility functions in the official scanner should be considered private API, in a sense. We make no effort to document or control their interfaces or behaviors externally, so if a third party dev wants to use them there's of course nothing preventing that, but they also accept a certain amount of risk when doing so. I'm really sorry this particular issue bit you, and it would be awesome if you'd be willing to help communicate that general philosophy to the community.

Thanks again for your diligence. When we make changes to support absolute ordering I'll definitely make sure you're in the loop.
