### ISSUE TITLE
Music Scanning: Does not look for Artist posters/backgrounds

### ISSUE THREAD

**Issue by SmithPlatts** [plexinc-plugins/Scanners.bundle#65]
| **NOTE** If this is more appropriate to agents, I am happy to close the issue here

When using the *Local Media Assets* agent to manage music files (**Artist** or **Album**), it does not respect the inclusion of an artists *Poster* and/or *Background* file (i.e. `artist.jpg`, `artist-poster.jpg`) for use within the Media Library.

Is this omission intentional? If not, can it be investigated?

I would fork and explore myself but I sadly do not have the time with 3 kids and a day job; sorry.

**Comment by sandman4sure** [comment]
What version of the Plex media server are you using? How does your folder structure looks like?

**Comment by SmithPlatts** [comment]
I have Plex Media Server for Windows `0.9.12.19` installed on Windows 10 64-bit.

Plex is looking at my iTunes Media location for files, which are managed in the standard tree structure:

- **iTunes Media**
  - **Artist1**
    - **Album**
      - `Track1.ext`, *etc*
  - **Artist2**
    - **Album**
      - `Track1.ext`, *etc*

In the Plex library configuration, I have configured *use embedded tags* as all the required data is in there for album and track sorting, covers/posters, etc. What I cannot put in the file data is an artist poster, this is why I tried adding a file to the structure:

- **iTunes Media**
  - **Artist1**
    - `artist.jpg`
    - **Album**
      - `Track1.ext`, *etc*
  - **Artist2**
    - `artist-poster.jpg`
    - **Album**
      - `Track1.ext`, *etc*

Is the issue with the library configuration *use embedded tags*?

Besides the artist poster, everything else is sorted and managed perfectly.

**Comment by sandman4sure** [comment]
Artist art support will be available in an upcoming release. I'm not sure which one, but not on `0.9.12.9` yet.

**Comment by SmithPlatts** [comment]
Cheers @sandman4sure :)

**Comment by Bunkermentality** [comment]
Windows PMS release now at 1.4.2.3400  and artist-background still not working very well. Any further news re availability on a forthcoming release?
