### ISSUE TITLE
.plexignore Not Excluding Directories When Using Asterisks (Perhaps Leading Asterisks Fail)

### ISSUE THREAD

**Issue by DerekFoulk** [plexinc-plugins/Scanners.bundle#69]
Hi guys,

I cannot get this .plexignore file to work... According to Issue #37, I think my .plexignore file should be excluding anything in a subdirectory that contains 'Extras', but it does not filter them from my library.

**Platform:** Windows Server 2012 R2
**Plex Version:** 0.9.12.19

Sample directory structure:

    D:\Movies
      \Hercules (2014) [Extended] [1080p] {7.1} [Someone]
        \Hercules.Extras-Someone
          \Brett.Ratner.and.Dwayne.Johnson-An.Introduction-Someone.mkv

Steps to reproduce:
1. Create the directories
2. Add a .mkv with any name to the `D:\Movies\Hercules (2014) [Extended] [1080p] {7.1} [Someone]\Hercules.Extras-Someone` directory
3. Update Plex library _(add content from step 2 to Plex library)_
4. Create the following .plexignore file in the `D:\Movies` folder:

    # Ignore directories containing 'extras'
    *Extras*/*
    *extras*/*
    *EXTRAS*/*

5. Update Plex library _(attempt to apply .plexignore filtering)_
6. Logout of Plex
7. Log back into Plex

The files from inside the `...\Hercules.Extras-Someone` remain in my library. My guess is the exclusion is failing due to the leading asterisk(s). Perhaps asterisks in the directory name don't work anywhere. I admit, I expected this file to work similar to Github's '.gitignore', and I'm attempting to use it as such, but it doesn't want to work for me.

Thanks in advance for any help! If this glob pattern worked, it would save me from having to specify each 'extras' specifically (assuming that would work).

**Comment by DerekFoulk** [comment]
After update to Plex 0.9.16.3 (PlexPass User), issue persists.

**Comment by maxGreenblatt** [comment]
Sorry about this - there has been some churn in the `.plexignore` world. There is a(nother) fix coming in the next update that should fix this issue.

**Comment by phreichmuth** [comment]
Make shure the .plexignore file is world-readable on the server. That was the issue on my Plex server on the my Qnap NAS. Hence, it was ignored.... Adding world readaccess did the trick.
