### ISSUE TITLE
Remove file extension when file is a number

### ISSUE THREAD

**Issue by nitschkecm** [plexinc-plugins/Scanners.bundle#71]
I have a large collection of video files which are indexed simply by a number which allows me to match them very well. When I use the standard plex movie scanner / Plex Video Files Scanner I get a title which is calle XXXXXXX MP4. I would like to avoid to have the MP4 or whichever file ending I have in the title. 

How could this be done?

**Comment by maxGreenblatt** [comment]
I believe the best way to do this would be to write your own third party scanner that removes the file extension from the name of the file.

Basically, we create the `name` of the file here: https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Movies/Plex%20Video%20Files%20Scanner.py#L15

And you could run a `replace` on a list similar to this one, to strip known video file endings: https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Common/VideoFiles.py#L5

**Comment by maxGreenblatt** [comment]
As this isn't really a bug and more of a request for something we won't be doing in the main scanner, I am going to close this issue.
